### ISSUE TITLE
Terminal doesn't reset after exiting hopa

### ISSUE THREAD

**Issue by JasonBristol** [krasimir/hopa#2]
When you run hopa, and then exit hopa, either through the menu or via ctrl+c, the terminal does not reset properly.

I have tested this on both windows and macos and have experienced different effects, most notably duplicated keystrokes on windows and being unable to scroll through the terminal on macos.

Running `reset` on macos fixes the issue

![2020-01-16 02-22-24 2020-01-16 02_24_40](https://user-images.githubusercontent.com/3958523/72502486-6b0a8700-3807-11ea-88a6-b4bd7c99e046.gif)

**Comment by krasimir** [comment]
Just released 1.3.1. Should be fixed now.

**Comment by JasonBristol** [comment]
Hey @krasimir, it looks like this is still an issue with 1.3.1, after exiting hopa scrolling within the terminal ends up scrolling through command history instead of  through the buffer (see above gif for an example)

**Comment by krasimir** [comment]
I see. What's this terminal app. iTerm?

**Comment by AliAlmohsen** [comment]
Just checked and I'm facing the following issue on my regular terminal on Linux Mint:
run `hopa`, press Ctrl+C. You end up with text on the lines after where you enter a command. You can always just run clear to fix things again (much faster and more of the intended action than reset).
![Screenshot from 2020-01-19 16-01-51](https://user-images.githubusercontent.com/51526307/72681480-1a2fb280-3ad5-11ea-8d0a-af3ed277c519.png)

**Comment by JasonBristol** [comment]
@krasimir Yah thats iTerm, I just double checked and can see this happening in the default terminal app as well.

Just to make sure this isn't zsh I tested in bash and faced the same issue

**Comment by krasimir** [comment]
Can you guys try again with the latest `1.3.2` version. I added `.reset` of the terminal on exit. cc @JasonBristol @AliRain

**Comment by AliAlmohsen** [comment]
My portion of the issue has been resolved, thanks for the hard work and dedication to the project! <3

**Comment by JasonBristol** [comment]
Sorry for the delay, I can confirm that 1.3.2 fixed the issue, thanks again!
